# Generated by Django 5.2.6 on 2025-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('outgoing', 'Outgoing')], max_length=10, null=True),
        ),
    ]
