# Generated by Django 5.2.6 on 2025-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometransaction',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='category',
            field=models.CharField(),
        ),
    ]
