# Generated by Django 5.2.6 on 2025-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0002_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometransaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Anual', 'Anual'), ('Único', 'Único')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Anual', 'Anual'), ('Único', 'Único')], max_length=50, null=True),
        ),
    ]
