# Generated by Django 5.2.6 on 2025-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0002_alter_incometransaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outgoingtransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
