# Generated by Django 5.2.6 on 2025-10-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0003_incometransaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometransaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
