# Generated by Django 5.2.6 on 2025-10-23 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0003_incometransaction_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persistence.category'),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Persistence.category'),
        ),
    ]
