# Generated by Django 5.2.6 on 2025-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persistence', '0004_alter_incometransaction_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometransaction',
            name='value',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='outgoingtransaction',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
